# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

INSERT INTO `departement` (`departement_code`, `departement_nom`, `departement_nom_uppercase`, `departement_slug`, `departement_nom_soundex`) VALUES
('17', 'Charente-Maritime', 'CHARENTE-MARITIME', 'charente-maritime', 'C6535635'),
('35', 'Ile-et-Vilaine', 'ILE-ET-VILAINE', 'ile-et-vilaine', 'I43145'),
('44', 'Loire-Atlantique', 'LOIRE-ATLANTIQUE', 'loire-atlantique', 'L634532'),
('49', 'Maine-et-Loire', 'MAINE-ET-LOIRE', 'maine-et-loire', 'M346'),
('53', 'Mayenne', 'MAYENNE', 'mayenne', 'M000'),
('56', 'Morbihan', 'MORBIHAN', 'morbihan', 'M615'),
('79', 'Deux-Sèvres', 'DEUX-SÈVRES', 'deux-sevres', 'D2162'),
('85', 'Vendée', 'VENDÉE', 'vendee', 'V530');

INSERT INTO `droits` (`droits_id`,`droits_intitule`) VALUES
(1,'Témoins'),
(2,'Expert'),
(3,'Admin');

INSERT INTO `confidentialite` (`confidentialite_id`,`confidentialite_intitule`,`confidentialite_explication`) VALUES
(1,'Libre','Vous authorisez vos témoignages à être transmis à d''autres associations, être publiés, etc.'),
(2,'Au cas par cas','Vous désirez que l''on vous demande l''autorisation avant chaque publication de vos témoignages'),
(3,'Confidentiel','Vous désirez que vos témoignages restent uniquement dans la base de données de l''AER');

INSERT INTO `utms` (`utm`, `maille20x20`, `maille50x50`, `maille100x100`) VALUES
('WS47', 'WSCD', 'WSNW', 'WS'),
('WS57', 'WSCD', 'WSNE', 'WS'),
('WS68', 'WSDE', 'WSNE', 'WS'),
('WS69', 'WSDE', 'WSNE', 'WS'),
('WS77', 'WSDD', 'WSNE', 'WS'),
('WS78', 'WSDE', 'WSNE', 'WS'),
('WS79', 'WSDE', 'WSNE', 'WS'),
('WS85', 'WSEC', 'WSNE', 'WS'),
('WS86', 'WSED', 'WSNE', 'WS'),
('WS87', 'WSED', 'WSNE', 'WS'),
('WS88', 'WSEE', 'WSNE', 'WS'),
('WS89', 'WSEE', 'WSNE', 'WS'),
('WS94', 'WSEC', 'WSSE', 'WS'),
('WS95', 'WSEC', 'WSNE', 'WS'),
('WS96', 'WSED', 'WSNE', 'WS'),
('WS97', 'WSED', 'WSNE', 'WS'),
('WS98', 'WSEE', 'WSNE', 'WS'),
('WS99', 'WSEE', 'WSNE', 'WS'),
('WT25', 'WTBC', 'WTNW', 'WT'),
('WT33', 'WTBB', 'WTSW', 'WT'),
('WT34', 'WTBC', 'WTSW', 'WT'),
('WT35', 'WTBC', 'WTNW', 'WT'),
('WT41', 'WTCA', 'WTSW', 'WT'),
('WT43', 'WTCB', 'WTSW', 'WT'),
('WT44', 'WTCC', 'WTSW', 'WT'),
('WT45', 'WTCC', 'WTNW', 'WT'),
('WT50', 'WTCA', 'WTSE', 'WT'),
('WT51', 'WTCA', 'WTSE', 'WT'),
('WT52', 'WTCB', 'WTSE', 'WT'),
('WT53', 'WTCB', 'WTSE', 'WT'),
('WT54', 'WTCC', 'WTSE', 'WT'),
('WT55', 'WTCC', 'WTNE', 'WT'),
('WT56', 'WTCD', 'WTNE', 'WT'),
('WT60', 'WTDA', 'WTSE', 'WT'),
('WT61', 'WTDA', 'WTSE', 'WT'),
('WT62', 'WTDB', 'WTSE', 'WT'),
('WT63', 'WTDB', 'WTSE', 'WT'),
('WT64', 'WTDC', 'WTSE', 'WT'),
('WT65', 'WTDC', 'WTNE', 'WT'),
('WT66', 'WTDD', 'WTNE', 'WT'),
('WT67', 'WTDD', 'WTNE', 'WT'),
('WT70', 'WTDA', 'WTSE', 'WT'),
('WT71', 'WTDA', 'WTSE', 'WT'),
('WT72', 'WTDB', 'WTSE', 'WT'),
('WT73', 'WTDB', 'WTSE', 'WT'),
('WT74', 'WTDC', 'WTSE', 'WT'),
('WT75', 'WTDC', 'WTNE', 'WT'),
('WT76', 'WTDD', 'WTNE', 'WT'),
('WT77', 'WTDD', 'WTNE', 'WT'),
('WT78', 'WTDE', 'WTNE', 'WT'),
('WT80', 'WTEA', 'WTSE', 'WT'),
('WT81', 'WTEA', 'WTSE', 'WT'),
('WT82', 'WTEB', 'WTSE', 'WT'),
('WT83', 'WTEB', 'WTSE', 'WT'),
('WT84', 'WTEC', 'WTSE', 'WT'),
('WT85', 'WTEC', 'WTNE', 'WT'),
('WT86', 'WTED', 'WTNE', 'WT'),
('WT87', 'WTED', 'WTNE', 'WT'),
('WT88', 'WTEE', 'WTNE', 'WT'),
('WT90', 'WTEA', 'WTSE', 'WT'),
('WT91', 'WTEA', 'WTSE', 'WT'),
('WT92', 'WTEB', 'WTSE', 'WT'),
('WT93', 'WTEB', 'WTSE', 'WT'),
('WT94', 'WTEC', 'WTSE', 'WT'),
('WT95', 'WTEC', 'WTNE', 'WT'),
('WT96', 'WTED', 'WTNE', 'WT'),
('WT97', 'WTED', 'WTNE', 'WT'),
('WT98', 'WTEE', 'WTNE', 'WT'),
('XS04', 'XSAC', 'XSSW', 'XS'),
('XS05', 'XSAC', 'XSNW', 'XS'),
('XS06', 'XSAD', 'XSNW', 'XS'),
('XS07', 'XSAD', 'XSNW', 'XS'),
('XS08', 'XSAE', 'XSNW', 'XS'),
('XS09', 'XSAE', 'XSNW', 'XS'),
('XS13', 'XSAB', 'XSSW', 'XS'),
('XS14', 'XSAC', 'XSSW', 'XS'),
('XS15', 'XSAC', 'XSNW', 'XS'),
('XS16', 'XSAD', 'XSNW', 'XS'),
('XS17', 'XSAD', 'XSNW', 'XS'),
('XS18', 'XSAE', 'XSNW', 'XS'),
('XS19', 'XSAE', 'XSNW', 'XS'),
('XS23', 'XSBB', 'XSSW', 'XS'),
('XS24', 'XSBC', 'XSSW', 'XS'),
('XS25', 'XSBC', 'XSNW', 'XS'),
('XS26', 'XSBD', 'XSNW', 'XS'),
('XS27', 'XSBD', 'XSNW', 'XS'),
('XS28', 'XSBE', 'XSNW', 'XS'),
('XS29', 'XSBE', 'XSNW', 'XS'),
('XS32', 'XSBB', 'XSSW', 'XS'),
('XS33', 'XSBB', 'XSSW', 'XS'),
('XS34', 'XSBC', 'XSSW', 'XS'),
('XS35', 'XSBC', 'XSNW', 'XS'),
('XS36', 'XSBD', 'XSNW', 'XS'),
('XS37', 'XSBD', 'XSNW', 'XS'),
('XS38', 'XSBE', 'XSNW', 'XS'),
('XS39', 'XSBE', 'XSNW', 'XS'),
('XS43', 'XSCB', 'XSSW', 'XS'),
('XS44', 'XSCC', 'XSSW', 'XS'),
('XS45', 'XSCC', 'XSNW', 'XS'),
('XS46', 'XSCD', 'XSNW', 'XS'),
('XS47', 'XSCD', 'XSNW', 'XS'),
('XS48', 'XSCE', 'XSNW', 'XS'),
('XS49', 'XSCE', 'XSNW', 'XS'),
('XS53', 'XSCB', 'XSSE', 'XS'),
('XS54', 'XSCC', 'XSSE', 'XS'),
('XS55', 'XSCC', 'XSNE', 'XS'),
('XS56', 'XSCD', 'XSNE', 'XS'),
('XS57', 'XSCD', 'XSNE', 'XS'),
('XS58', 'XSCE', 'XSNE', 'XS'),
('XS59', 'XSCE', 'XSNE', 'XS'),
('XS63', 'XSDB', 'XSSE', 'XS'),
('XS64', 'XSDC', 'XSSE', 'XS'),
('XS65', 'XSDC', 'XSNE', 'XS'),
('XS66', 'XSDD', 'XSNE', 'XS'),
('XS67', 'XSDD', 'XSNE', 'XS'),
('XS68', 'XSDE', 'XSNE', 'XS'),
('XS69', 'XSDE', 'XSNE', 'XS'),
('XS73', 'XSDB', 'XSSE', 'XS'),
('XS74', 'XSDC', 'XSSE', 'XS'),
('XS75', 'XSDC', 'XSNE', 'XS'),
('XS76', 'XSDD', 'XSNE', 'XS'),
('XS77', 'XSDD', 'XSNE', 'XS'),
('XS78', 'XSDE', 'XSNE', 'XS'),
('XS83', 'XSEB', 'XSSE', 'XS'),
('XS84', 'XSEC', 'XSSE', 'XS'),
('XS85', 'XSEC', 'XSNE', 'XS'),
('XS86', 'XSED', 'XSNE', 'XS'),
('XS87', 'XSED', 'XSNE', 'XS'),
('XT00', 'XTAA', 'XTSW', 'XT'),
('XT01', 'XTAA', 'XTSW', 'XT'),
('XT02', 'XTAB', 'XTSW', 'XT'),
('XT03', 'XTAB', 'XTSW', 'XT'),
('XT04', 'XTAC', 'XTSW', 'XT'),
('XT05', 'XTAC', 'XTNW', 'XT'),
('XT06', 'XTAD', 'XTNW', 'XT'),
('XT07', 'XTAD', 'XTNW', 'XT'),
('XT08', 'XTAE', 'XTNW', 'XT'),
('XT09', 'XTAE', 'XTNW', 'XT'),
('XT10', 'XTAA', 'XTSW', 'XT'),
('XT11', 'XTAA', 'XTSW', 'XT'),
('XT12', 'XTAB', 'XTSW', 'XT'),
('XT13', 'XTAB', 'XTSW', 'XT'),
('XT14', 'XTAC', 'XTSW', 'XT'),
('XT15', 'XTAC', 'XTNW', 'XT'),
('XT16', 'XTAD', 'XTNW', 'XT'),
('XT17', 'XTAD', 'XTNW', 'XT'),
('XT18', 'XTAE', 'XTNW', 'XT'),
('XT19', 'XTAE', 'XTNW', 'XT'),
('XT20', 'XTBA', 'XTSW', 'XT'),
('XT21', 'XTBA', 'XTSW', 'XT'),
('XT22', 'XTBB', 'XTSW', 'XT'),
('XT23', 'XTBB', 'XTSW', 'XT'),
('XT24', 'XTBC', 'XTSW', 'XT'),
('XT25', 'XTBC', 'XTNW', 'XT'),
('XT26', 'XTBD', 'XTNW', 'XT'),
('XT27', 'XTBD', 'XTNW', 'XT'),
('XT28', 'XTBE', 'XTNW', 'XT'),
('XT29', 'XTBE', 'XTNW', 'XT'),
('XT30', 'XTBA', 'XTSW', 'XT'),
('XT31', 'XTBA', 'XTSW', 'XT'),
('XT32', 'XTBB', 'XTSW', 'XT'),
('XT33', 'XTBB', 'XTSW', 'XT'),
('XT34', 'XTBC', 'XTSW', 'XT'),
('XT35', 'XTBC', 'XTNW', 'XT'),
('XT36', 'XTBD', 'XTNW', 'XT'),
('XT37', 'XTBD', 'XTNW', 'XT'),
('XT38', 'XTBE', 'XTNW', 'XT'),
('XT39', 'XTBE', 'XTNW', 'XT'),
('XT40', 'XTCA', 'XTSW', 'XT'),
('XT41', 'XTCA', 'XTSW', 'XT'),
('XT44', 'XTCC', 'XTSW', 'XT'),
('XT45', 'XTCC', 'XTNW', 'XT'),
('XT46', 'XTCD', 'XTNW', 'XT'),
('XT47', 'XTCD', 'XTNW', 'XT'),
('XT50', 'XTCA', 'XTSE', 'XT'),
('XT54', 'XTCC', 'XTSE', 'XT'),
('XT55', 'XTCC', 'XTNE', 'XT'),
('XT56', 'XTCD', 'XTNE', 'XT'),
('XT60', 'XTDA', 'XTSE', 'XT');

# --- !Downs

SET FOREIGN_KEY_CHECKS=0;

DELETE FROM departement;
DELETE FROM droits;
DELETE FROM confidentialite;
DELETE FROM utms;

SET FOREIGN_KEY_CHECKS=1;


